version: '3.3'

services:
  approvalcenter.services.api:
    image: oliveiramarcos/approvalcenterapi
    container_name: approvalcenterapi
    ports:
      - "1080:80"
      - "1081:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=1081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=approvalcenter_dev
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert-aspnetcore.pfx
    build:
      context: .
      dockerfile: src/ApprovalCenter.Services.Api/Dockerfile
    networks:
      - approval-network

networks:
  approval-network:
    driver: bridge
